//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BazWebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisplayNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BazWebApp.Resources.DisplayNames", typeof(DisplayNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Ad {
            get {
                return ResourceManager.GetString("Ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Adi {
            get {
                return ResourceManager.GetString("Adi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Adres {
            get {
                return ResourceManager.GetString("Adres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Type.
        /// </summary>
        public static string AdresTipi {
            get {
                return ResourceManager.GetString("AdresTipi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Explanation.
        /// </summary>
        public static string AksiyonAciklama {
            get {
                return ResourceManager.GetString("AksiyonAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Group Reference Number.
        /// </summary>
        public static string AksiyonGrupReferansNo {
            get {
                return ResourceManager.GetString("AksiyonGrupReferansNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Group Definition.
        /// </summary>
        public static string AksiyonGrupTanimi {
            get {
                return ResourceManager.GetString("AksiyonGrupTanimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Target Group Definition Grouping Reference Number.
        /// </summary>
        public static string AksiyonHedefKitleTanimGruplamaReferansNo {
            get {
                return ResourceManager.GetString("AksiyonHedefKitleTanimGruplamaReferansNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions to be Grouped.
        /// </summary>
        public static string AksiyonIDList {
            get {
                return ResourceManager.GetString("AksiyonIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Related Media Note.
        /// </summary>
        public static string AksiyonMedyaIlgiliNot {
            get {
                return ResourceManager.GetString("AksiyonMedyaIlgiliNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Confirm Grouping Reference Number.
        /// </summary>
        public static string AksiyonOnayGruplamaReferansNo {
            get {
                return ResourceManager.GetString("AksiyonOnayGruplamaReferansNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Confirm Process Note.
        /// </summary>
        public static string AksiyonOnayIslemNotu {
            get {
                return ResourceManager.GetString("AksiyonOnayIslemNotu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approving Role or Position.
        /// </summary>
        public static string AksiyonOnayMerciKurumOrganizasyonBirimId {
            get {
                return ResourceManager.GetString("AksiyonOnayMerciKurumOrganizasyonBirimId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Approval Definition.
        /// </summary>
        public static string AksiyonOnayTanim {
            get {
                return ResourceManager.GetString("AksiyonOnayTanim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action URL to be Shared .
        /// </summary>
        public static string AksiyonPaylasilacakUrl {
            get {
                return ResourceManager.GetString("AksiyonPaylasilacakUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Plan Note.
        /// </summary>
        public static string AksiyonPlaniNot {
            get {
                return ResourceManager.GetString("AksiyonPlaniNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Planning Term Explanation.
        /// </summary>
        public static string AksiyonPlanlamaDonemiAciklama {
            get {
                return ResourceManager.GetString("AksiyonPlanlamaDonemiAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Planning Term.
        /// </summary>
        public static string AksiyonPlanlamaDonemiD {
            get {
                return ResourceManager.GetString("AksiyonPlanlamaDonemiD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Planning Term Definition.
        /// </summary>
        public static string AksiyonPlanlamaDonemiTanimi {
            get {
                return ResourceManager.GetString("AksiyonPlanlamaDonemiTanimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Group.
        /// </summary>
        public static string AksiyonPlanlananHedefKitleID {
            get {
                return ResourceManager.GetString("AksiyonPlanlananHedefKitleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Company.
        /// </summary>
        public static string AksiyonPlanlananHedefKurumID {
            get {
                return ResourceManager.GetString("AksiyonPlanlananHedefKurumID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned Actions General Id.
        /// </summary>
        public static string AksiyonPlanlananlarGenelID {
            get {
                return ResourceManager.GetString("AksiyonPlanlananlarGenelID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned Action Media Note.
        /// </summary>
        public static string AksiyonPlanlananMedyaNotu {
            get {
                return ResourceManager.GetString("AksiyonPlanlananMedyaNotu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning Role or Position.
        /// </summary>
        public static string AksiyonPlanlayanOrganizasyonBirimID {
            get {
                return ResourceManager.GetString("AksiyonPlanlayanOrganizasyonBirimID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Color Code.
        /// </summary>
        public static string AksiyonRenkKodu {
            get {
                return ResourceManager.GetString("AksiyonRenkKodu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Definition.
        /// </summary>
        public static string AksiyonTanim {
            get {
                return ResourceManager.GetString("AksiyonTanim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Definition General Id.
        /// </summary>
        public static string AksiyonTanimGenelID {
            get {
                return ResourceManager.GetString("AksiyonTanimGenelID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Types.
        /// </summary>
        public static string AksiyonTipiId {
            get {
                return ResourceManager.GetString("AksiyonTipiId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother&apos;s Name.
        /// </summary>
        public static string AnneAdi {
            get {
                return ResourceManager.GetString("AnneAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API URL.
        /// </summary>
        public static string Apiurl {
            get {
                return ResourceManager.GetString("Apiurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father&apos;s Name.
        /// </summary>
        public static string BabaAdi {
            get {
                return ResourceManager.GetString("BabaAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Explanation.
        /// </summary>
        public static string BelgeAciklama {
            get {
                return ResourceManager.GetString("BelgeAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Definition.
        /// </summary>
        public static string BelgeTanim {
            get {
                return ResourceManager.GetString("BelgeTanim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Contacts to Notify.
        /// </summary>
        public static string BildirimGonderilecekKisiList {
            get {
                return ResourceManager.GetString("BildirimGonderilecekKisiList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Text.
        /// </summary>
        public static string BildirimMetni {
            get {
                return ResourceManager.GetString("BildirimMetni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Time.
        /// </summary>
        public static string BildirimZamani {
            get {
                return ResourceManager.GetString("BildirimZamani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Short Definition.
        /// </summary>
        public static string BirimKisaTanim {
            get {
                return ResourceManager.GetString("BirimKisaTanim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Definition.
        /// </summary>
        public static string BirimTanim {
            get {
                return ResourceManager.GetString("BirimTanim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Definition Name.
        /// </summary>
        public static string BirimTanimiAdi {
            get {
                return ResourceManager.GetString("BirimTanimiAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiliated Person.
        /// </summary>
        public static string BuKisiID {
            get {
                return ResourceManager.GetString("BuKisiID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiliated Company.
        /// </summary>
        public static string BuKurumID {
            get {
                return ResourceManager.GetString("BuKurumID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Associated With.
        /// </summary>
        public static string BununKisiID {
            get {
                return ResourceManager.GetString("BununKisiID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Associated With.
        /// </summary>
        public static string BununKurumID {
            get {
                return ResourceManager.GetString("BununKurumID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string CepTelefonNumarasi {
            get {
                return ResourceManager.GetString("CepTelefonNumarasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Code.
        /// </summary>
        public static string ChannelCode {
            get {
                return ResourceManager.GetString("ChannelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Cinsiyeti {
            get {
                return ResourceManager.GetString("Cinsiyeti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şehir.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geography Explanation.
        /// </summary>
        public static string CografyaAciklama {
            get {
                return ResourceManager.GetString("CografyaAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geography Area Explanation.
        /// </summary>
        public static string CografyaAlaniAciklama {
            get {
                return ResourceManager.GetString("CografyaAlaniAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geography Area Definition.
        /// </summary>
        public static string CografyaAlaniTanimi {
            get {
                return ResourceManager.GetString("CografyaAlaniTanimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geography Definition.
        /// </summary>
        public static string CografyaTanim {
            get {
                return ResourceManager.GetString("CografyaTanim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        public static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concat.
        /// </summary>
        public static string Concat {
            get {
                return ResourceManager.GetString("Concat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Soyad.
        /// </summary>
        public static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ülke.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom API Name.
        /// </summary>
        public static string CustomApiName {
            get {
                return ResourceManager.GetString("CustomApiName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Deger {
            get {
                return ResourceManager.GetString("Deger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Departman {
            get {
                return ResourceManager.GetString("Departman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Space.
        /// </summary>
        public static string DepolamaAlani {
            get {
                return ResourceManager.GetString("DepolamaAlani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slicing Interval Duration.
        /// </summary>
        public static string DilimAraliklariSuresiDakika {
            get {
                return ResourceManager.GetString("DilimAraliklariSuresiDakika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slicing Start Date.
        /// </summary>
        public static string DilimlendirmeBaslangicTarihi {
            get {
                return ResourceManager.GetString("DilimlendirmeBaslangicTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slicing End Date.
        /// </summary>
        public static string DilimlendirmeBitisTarihi {
            get {
                return ResourceManager.GetString("DilimlendirmeBitisTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slicing Color Code.
        /// </summary>
        public static string DilimlerRenkKodu {
            get {
                return ResourceManager.GetString("DilimlerRenkKodu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Level.
        /// </summary>
        public static string DilSeviye {
            get {
                return ResourceManager.GetString("DilSeviye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Level.
        /// </summary>
        public static string DilSeviyesi {
            get {
                return ResourceManager.GetString("DilSeviyesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regilion.
        /// </summary>
        public static string Dini {
            get {
                return ResourceManager.GetString("Dini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City of Birth.
        /// </summary>
        public static string DogduguSehir {
            get {
                return ResourceManager.GetString("DogduguSehir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country of Birth.
        /// </summary>
        public static string DogduguUlke {
            get {
                return ResourceManager.GetString("DogduguUlke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term Start Date.
        /// </summary>
        public static string DonemBaslangicTarihi {
            get {
                return ResourceManager.GetString("DonemBaslangicTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term End Date.
        /// </summary>
        public static string DonemBitisTarihi {
            get {
                return ResourceManager.GetString("DonemBitisTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period Appearance Start Date.
        /// </summary>
        public static string DonemGorunmeBaslangicZamani {
            get {
                return ResourceManager.GetString("DonemGorunmeBaslangicZamani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period Appearance End Date.
        /// </summary>
        public static string DonemGorunmeBitisZamani {
            get {
                return ResourceManager.GetString("DonemGorunmeBitisZamani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term Notation Color.
        /// </summary>
        public static string DonemGosterimRengi {
            get {
                return ResourceManager.GetString("DonemGosterimRengi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion Rate Source.
        /// </summary>
        public static string DonusumOraniKaynagi {
            get {
                return ResourceManager.GetString("DonusumOraniKaynagi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date.
        /// </summary>
        public static string EDate {
            get {
                return ResourceManager.GetString("EDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail or Username.
        /// </summary>
        public static string EmailOrUserName {
            get {
                return ResourceManager.GetString("EmailOrUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail Address.
        /// </summary>
        public static string EpostaAdresi {
            get {
                return ResourceManager.GetString("EpostaAdresi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Types.
        /// </summary>
        public static string ErisimYetkisiVerilenAksiyonId {
            get {
                return ResourceManager.GetString("ErisimYetkisiVerilenAksiyonId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string ErisimYetkisiVerilenSayfaIdList {
            get {
                return ResourceManager.GetString("ErisimYetkisiVerilenSayfaIdList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interaction Post Message.
        /// </summary>
        public static string EtkilesimPostMessage {
            get {
                return ResourceManager.GetString("EtkilesimPostMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interaction Post URL.
        /// </summary>
        public static string EtkilesimPostUrl {
            get {
                return ResourceManager.GetString("EtkilesimPostUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interaction Response Message.
        /// </summary>
        public static string EtkilesimResponseMessage {
            get {
                return ResourceManager.GetString("EtkilesimResponseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interaction Response URL.
        /// </summary>
        public static string EtkilesimResponseUrl {
            get {
                return ResourceManager.GetString("EtkilesimResponseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty.
        /// </summary>
        public static string Fakulte {
            get {
                return ResourceManager.GetString("Fakulte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Number.
        /// </summary>
        public static string FaturaNo {
            get {
                return ResourceManager.GetString("FaturaNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string FaxNo {
            get {
                return ResourceManager.GetString("FaxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Type.
        /// </summary>
        public static string GonderimTipi {
            get {
                return ResourceManager.GetString("GonderimTipi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference Sub Session Number.
        /// </summary>
        public static string GorusmeAltOturumNo {
            get {
                return ResourceManager.GetString("GorusmeAltOturumNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference Main Session Number.
        /// </summary>
        public static string GorusmeAnaOturumNo {
            get {
                return ResourceManager.GetString("GorusmeAnaOturumNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string GorusmeBaslangicZamani {
            get {
                return ResourceManager.GetString("GorusmeBaslangicZamani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string GorusmeBitisZamani {
            get {
                return ResourceManager.GetString("GorusmeBitisZamani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference Drawing Registration Reference Number.
        /// </summary>
        public static string GorusmeCizimKayitReferansNo {
            get {
                return ResourceManager.GetString("GorusmeCizimKayitReferansNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference Participation Point IP.
        /// </summary>
        public static string GorusmeKatilimNoktasiIp {
            get {
                return ResourceManager.GetString("GorusmeKatilimNoktasiIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Recording Time.
        /// </summary>
        public static string GorusmeKaydiSuresi {
            get {
                return ResourceManager.GetString("GorusmeKaydiSuresi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference Registration Reference Number.
        /// </summary>
        public static string GorusmeKayitReferansNo {
            get {
                return ResourceManager.GetString("GorusmeKayitReferansNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference Room Explanation.
        /// </summary>
        public static string GorusmeOdasiAciklama {
            get {
                return ResourceManager.GetString("GorusmeOdasiAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference Room Sub Session Number.
        /// </summary>
        public static string GorusmeOdasiAltOturumNo {
            get {
                return ResourceManager.GetString("GorusmeOdasiAltOturumNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference Room Main Session Number.
        /// </summary>
        public static string GorusmeOdasiAnaOturumNo {
            get {
                return ResourceManager.GetString("GorusmeOdasiAnaOturumNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference Room Chat Registration Reference Number.
        /// </summary>
        public static string GorusmeOdasiChatKayitReferansNo {
            get {
                return ResourceManager.GetString("GorusmeOdasiChatKayitReferansNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference Room Access URL.
        /// </summary>
        public static string GorusmeOdasiEisimUrl {
            get {
                return ResourceManager.GetString("GorusmeOdasiEisimUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference Room Definition.
        /// </summary>
        public static string GorusmeOdasiTanim {
            get {
                return ResourceManager.GetString("GorusmeOdasiTanim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference Room Traffic Value Text.
        /// </summary>
        public static string GorusmeOdasiTrafikDegerMetin {
            get {
                return ResourceManager.GetString("GorusmeOdasiTrafikDegerMetin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Maximum Call Time.
        /// </summary>
        public static string GrupMaxGorusmeSuresi {
            get {
                return ResourceManager.GetString("GrupMaxGorusmeSuresi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Update.
        /// </summary>
        public static string GuncellenmeTarihi {
            get {
                return ResourceManager.GetString("GuncellenmeTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Type.
        /// </summary>
        public static string HatirlatmaBaglantiliAksiyonTipiId {
            get {
                return ResourceManager.GetString("HatirlatmaBaglantiliAksiyonTipiId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder Text.
        /// </summary>
        public static string HatirlatmaMetni {
            get {
                return ResourceManager.GetString("HatirlatmaMetni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Group Explanation.
        /// </summary>
        public static string HedefKitleAciklama {
            get {
                return ResourceManager.GetString("HedefKitleAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Group Definition.
        /// </summary>
        public static string HedefKitleTanim {
            get {
                return ResourceManager.GetString("HedefKitleTanim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Group Rows Grouping Reference Number.
        /// </summary>
        public static string HedefKitleTanimSatirlariGruplandırmaReferansNo {
            get {
                return ResourceManager.GetString("HedefKitleTanimSatirlariGruplandırmaReferansNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Activation Page Temporary URL.
        /// </summary>
        public static string HesapAktivasyonSayfasiGeciciUrl {
            get {
                return ResourceManager.GetString("HesapAktivasyonSayfasiGeciciUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Title.
        /// </summary>
        public static string IcerikBaslik {
            get {
                return ResourceManager.GetString("IcerikBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content End Time.
        /// </summary>
        public static string IcerikBitisZamani {
            get {
                return ResourceManager.GetString("IcerikBitisZamani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Library Id.
        /// </summary>
        public static string IcerikKutuphanesiId {
            get {
                return ResourceManager.GetString("IcerikKutuphanesiId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Summary Text.
        /// </summary>
        public static string IcerikOzetMetni {
            get {
                return ResourceManager.GetString("IcerikOzetMetni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Color Code.
        /// </summary>
        public static string IcerikRenkKodu {
            get {
                return ResourceManager.GetString("IcerikRenkKodu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Content Text.
        /// </summary>
        public static string IcerikTamMetin {
            get {
                return ResourceManager.GetString("IcerikTamMetin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Definition.
        /// </summary>
        public static string IcerikTanim {
            get {
                return ResourceManager.GetString("IcerikTanim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Triggering Table Name.
        /// </summary>
        public static string IcerikTetikleyecekTabloAdi {
            get {
                return ResourceManager.GetString("IcerikTetikleyecekTabloAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Release Time.
        /// </summary>
        public static string IcerikYayinlanmaZamani {
            get {
                return ResourceManager.GetString("IcerikYayinlanmaZamani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string IlgiliKurumId {
            get {
                return ResourceManager.GetString("IlgiliKurumId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positions or Roles.
        /// </summary>
        public static string IlgiliKurumOrganizasyonBirimIdList {
            get {
                return ResourceManager.GetString("IlgiliKurumOrganizasyonBirimIdList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Unit Definition.
        /// </summary>
        public static string IlgiliKurumOrganizasyonBirimIdList1 {
            get {
                return ResourceManager.GetString("IlgiliKurumOrganizasyonBirimIdList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Parameter Name.
        /// </summary>
        public static string IlgiliParametreAdi {
            get {
                return ResourceManager.GetString("IlgiliParametreAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Parameter Table.
        /// </summary>
        public static string IlgilParametreTablo {
            get {
                return ResourceManager.GetString("IlgilParametreTablo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship Type.
        /// </summary>
        public static string IliskiTuruID {
            get {
                return ResourceManager.GetString("IliskiTuruID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant Group Explanation.
        /// </summary>
        public static string KatilimciGrupAciklama {
            get {
                return ResourceManager.GetString("KatilimciGrupAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant Group Definition.
        /// </summary>
        public static string KatilimciGrupTanim {
            get {
                return ResourceManager.GetString("KatilimciGrupTanim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Record.
        /// </summary>
        public static string KayitTarihi {
            get {
                return ResourceManager.GetString("KayitTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string KisiAdi {
            get {
                return ResourceManager.GetString("KisiAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Name.
        /// </summary>
        public static string KisiEkranAdi {
            get {
                return ResourceManager.GetString("KisiEkranAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string KisiEposta {
            get {
                return ResourceManager.GetString("KisiEposta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person List.
        /// </summary>
        public static string KisiIdList {
            get {
                return ResourceManager.GetString("KisiIdList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Phone.
        /// </summary>
        public static string KisiİsTelefon {
            get {
                return ResourceManager.GetString("KisiİsTelefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citizenship Number.
        /// </summary>
        public static string KisiKimlikNo {
            get {
                return ResourceManager.GetString("KisiKimlikNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string KisiKullaniciAdi {
            get {
                return ResourceManager.GetString("KisiKullaniciAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string KisiMail {
            get {
                return ResourceManager.GetString("KisiMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Number.
        /// </summary>
        public static string KisiPasaportNo {
            get {
                return ResourceManager.GetString("KisiPasaportNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password must contain at least 8 characters and at least 1 number, special characters (!,?) and uppercase letters..
        /// </summary>
        public static string KisiSifre {
            get {
                return ResourceManager.GetString("KisiSifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string KisiSoyadi {
            get {
                return ResourceManager.GetString("KisiSoyadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string KisiTelefon {
            get {
                return ResourceManager.GetString("KisiTelefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinats.
        /// </summary>
        public static string Koordinat {
            get {
                return ResourceManager.GetString("Koordinat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Timeout &amp; Mandatory Password Renewal Interval.
        /// </summary>
        public static string KureselParams {
            get {
                return ResourceManager.GetString("KureselParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Kurum {
            get {
                return ResourceManager.GetString("Kurum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string KurumAdi {
            get {
                return ResourceManager.GetString("KurumAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Account Deactivation Explanation.
        /// </summary>
        public static string KurumHesabiDeAktifAciklama {
            get {
                return ResourceManager.GetString("KurumHesabiDeAktifAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Choose.
        /// </summary>
        public static string KurumId {
            get {
                return ResourceManager.GetString("KurumId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Short Title.
        /// </summary>
        public static string KurumKisaUnvan {
            get {
                return ResourceManager.GetString("KurumKisaUnvan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Logo URL.
        /// </summary>
        public static string KurumResimUrl {
            get {
                return ResourceManager.GetString("KurumResimUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Commercial Title.
        /// </summary>
        public static string KurumTicariUnvani {
            get {
                return ResourceManager.GetString("KurumTicariUnvani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Tax Number.
        /// </summary>
        public static string KurumVergiNo {
            get {
                return ResourceManager.GetString("KurumVergiNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence Explanation.
        /// </summary>
        public static string LisansAciklama {
            get {
                return ResourceManager.GetString("LisansAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Price.
        /// </summary>
        public static string LisansBedeli {
            get {
                return ResourceManager.GetString("LisansBedeli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence Unique Number.
        /// </summary>
        public static string LisansEssizNo {
            get {
                return ResourceManager.GetString("LisansEssizNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string LisansId {
            get {
                return ResourceManager.GetString("LisansId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of License Persons.
        /// </summary>
        public static string LisansKisiSayisi {
            get {
                return ResourceManager.GetString("LisansKisiSayisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License User Count.
        /// </summary>
        public static string LisansPaketiKisiSayisi {
            get {
                return ResourceManager.GetString("LisansPaketiKisiSayisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence Rows Grouping Reference Number.
        /// </summary>
        public static string LisansSatirlariGruplamaReferansNo {
            get {
                return ResourceManager.GetString("LisansSatirlariGruplamaReferansNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence Definition.
        /// </summary>
        public static string LisansTanim {
            get {
                return ResourceManager.GetString("LisansTanim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Time.
        /// </summary>
        public static string LisansZamanId {
            get {
                return ResourceManager.GetString("LisansZamanId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login External System Token.
        /// </summary>
        public static string LoginDisSistemToken {
            get {
                return ResourceManager.GetString("LoginDisSistemToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Firebase Token.
        /// </summary>
        public static string LoginFirebaseToken {
            get {
                return ResourceManager.GetString("LoginFirebaseToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login System Token.
        /// </summary>
        public static string LoginSistemToken {
            get {
                return ResourceManager.GetString("LoginSistemToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Lokasyon {
            get {
                return ResourceManager.GetString("Lokasyon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Name.
        /// </summary>
        public static string LokasyonAdi {
            get {
                return ResourceManager.GetString("LokasyonAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Number of Participants.
        /// </summary>
        public static string MaxKatilimciSayisi {
            get {
                return ResourceManager.GetString("MaxKatilimciSayisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital Status.
        /// </summary>
        public static string MedeniHali {
            get {
                return ResourceManager.GetString("MedeniHali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Name.
        /// </summary>
        public static string MedyaAdi {
            get {
                return ResourceManager.GetString("MedyaAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media URL.
        /// </summary>
        public static string MedyaUrl {
            get {
                return ResourceManager.GetString("MedyaUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Explanation.
        /// </summary>
        public static string MenuAciklama {
            get {
                return ResourceManager.GetString("MenuAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Title.
        /// </summary>
        public static string MenuBasligi {
            get {
                return ResourceManager.GetString("MenuBasligi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Definition.
        /// </summary>
        public static string MenuTanimi {
            get {
                return ResourceManager.GetString("MenuTanimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Associate Url.
        /// </summary>
        public static string MesajIliskilendirilmisUrl {
            get {
                return ResourceManager.GetString("MesajIliskilendirilmisUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Text.
        /// </summary>
        public static string MesajMetni {
            get {
                return ResourceManager.GetString("MesajMetni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Serial Reference Number.
        /// </summary>
        public static string MesajSeriReferansNo {
            get {
                return ResourceManager.GetString("MesajSeriReferansNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Body.
        /// </summary>
        public static string Mesgbody {
            get {
                return ResourceManager.GetString("Mesgbody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional Title.
        /// </summary>
        public static string MeslekiUnvan {
            get {
                return ResourceManager.GetString("MeslekiUnvan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Value.
        /// </summary>
        public static string MetinDeger {
            get {
                return ResourceManager.GetString("MetinDeger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        public static string ModulId {
            get {
                return ResourceManager.GetString("ModulId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time-out Color Code.
        /// </summary>
        public static string MolaRenkKodu {
            get {
                return ResourceManager.GetString("MolaRenkKodu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password Repetition.
        /// </summary>
        public static string NewPasswordTekrar {
            get {
                return ResourceManager.GetString("NewPasswordTekrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Associate System Page URL.
        /// </summary>
        public static string NotIlgiliSistemSayfaUrl {
            get {
                return ResourceManager.GetString("NotIlgiliSistemSayfaUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Text.
        /// </summary>
        public static string NotMetni {
            get {
                return ResourceManager.GetString("NotMetni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Series Reference Number.
        /// </summary>
        public static string NotSerisiReferansNo {
            get {
                return ResourceManager.GetString("NotSerisiReferansNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers.
        /// </summary>
        public static string Numbers {
            get {
                return ResourceManager.GetString("Numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Name.
        /// </summary>
        public static string OkulAdi {
            get {
                return ResourceManager.GetString("OkulAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Type.
        /// </summary>
        public static string OkulTipi {
            get {
                return ResourceManager.GetString("OkulTipi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible Value Name.
        /// </summary>
        public static string OlasiDegerAdi {
            get {
                return ResourceManager.GetString("OlasiDegerAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Unit Name.
        /// </summary>
        public static string OrganizasyonBirimAdi {
            get {
                return ResourceManager.GetString("OrganizasyonBirimAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Unit.
        /// </summary>
        public static string OrganizasyonBirimiID {
            get {
                return ResourceManager.GetString("OrganizasyonBirimiID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Originator.
        /// </summary>
        public static string Originator {
            get {
                return ResourceManager.GetString("Originator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Day Explanation.
        /// </summary>
        public static string OzelGunAciklama {
            get {
                return ResourceManager.GetString("OzelGunAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Day Start Date.
        /// </summary>
        public static string OzelGunBaslangicTarihi {
            get {
                return ResourceManager.GetString("OzelGunBaslangicTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Day End Date.
        /// </summary>
        public static string OzelGunBitisTarihi {
            get {
                return ResourceManager.GetString("OzelGunBitisTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Day Type.
        /// </summary>
        public static string OzelGunTipID {
            get {
                return ResourceManager.GetString("OzelGunTipID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string OzelGunUlkeID {
            get {
                return ResourceManager.GetString("OzelGunUlkeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Name.
        /// </summary>
        public static string ParametreAdi {
            get {
                return ResourceManager.GetString("ParametreAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Text Value.
        /// </summary>
        public static string ParametreMetinDegeri {
            get {
                return ResourceManager.GetString("ParametreMetinDegeri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Code.
        /// </summary>
        public static string ParamKod {
            get {
                return ResourceManager.GetString("ParamKod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Definition.
        /// </summary>
        public static string ParamTanim {
            get {
                return ResourceManager.GetString("ParamTanim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password must contain at least 8 characters and at least 1 number, special characters (!,?) and uppercase letters..
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared URL.
        /// </summary>
        public static string PaylasilanUrl {
            get {
                return ResourceManager.GetString("PaylasilanUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharing Start Date.
        /// </summary>
        public static string PaylasimBaslangicTarihi {
            get {
                return ResourceManager.GetString("PaylasimBaslangicTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning Note.
        /// </summary>
        public static string PlanlamaNotu {
            get {
                return ResourceManager.GetString("PlanlamaNotu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned Person Id.
        /// </summary>
        public static string PlanlayanKisiID {
            get {
                return ResourceManager.GetString("PlanlayanKisiID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform Id.
        /// </summary>
        public static string PlatformID {
            get {
                return ResourceManager.GetString("PlatformID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postman Transaction Success Message.
        /// </summary>
        public static string PostaciIslemBasariMesaji {
            get {
                return ResourceManager.GetString("PostaciIslemBasariMesaji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postman Transaction Failure Message.
        /// </summary>
        public static string PostaciIslemHataMesaji {
            get {
                return ResourceManager.GetString("PostaciIslemHataMesaji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postman Process Reference Number.
        /// </summary>
        public static string PostaciIslemReferansNo {
            get {
                return ResourceManager.GetString("PostaciIslemReferansNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Message.
        /// </summary>
        public static string PostMessage {
            get {
                return ResourceManager.GetString("PostMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Pozisyon {
            get {
                return ResourceManager.GetString("Pozisyon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string PozisyonID {
            get {
                return ResourceManager.GetString("PozisyonID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Message.
        /// </summary>
        public static string ResponseMessage {
            get {
                return ResourceManager.GetString("ResponseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Rol {
            get {
                return ResourceManager.GetString("Rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Template Type.
        /// </summary>
        public static string SablonIcerikTipiId {
            get {
                return ResourceManager.GetString("SablonIcerikTipiId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Pos Unique Reference Number.
        /// </summary>
        public static string SanalPosessizReferansNo {
            get {
                return ResourceManager.GetString("SanalPosessizReferansNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Pos Post Message.
        /// </summary>
        public static string SanalPosPostMessage {
            get {
                return ResourceManager.GetString("SanalPosPostMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Pos Response Message.
        /// </summary>
        public static string SanalPosResponseMessage {
            get {
                return ResourceManager.GetString("SanalPosResponseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Name.
        /// </summary>
        public static string SayfaAdi {
            get {
                return ResourceManager.GetString("SayfaAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Associate Table.
        /// </summary>
        public static string SayfaBaglantiliTablo {
            get {
                return ResourceManager.GetString("SayfaBaglantiliTablo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string SayfaId {
            get {
                return ResourceManager.GetString("SayfaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Definition.
        /// </summary>
        public static string SayfaTanimi {
            get {
                return ResourceManager.GetString("SayfaTanimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page URL.
        /// </summary>
        public static string SayfaUrl {
            get {
                return ResourceManager.GetString("SayfaUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Date.
        /// </summary>
        public static string SDate {
            get {
                return ResourceManager.GetString("SDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Sehir {
            get {
                return ResourceManager.GetString("Sehir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Name.
        /// </summary>
        public static string SehirAdi {
            get {
                return ResourceManager.GetString("SehirAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string SehirlerIDList {
            get {
                return ResourceManager.GetString("SehirlerIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Number.
        /// </summary>
        public static string SicilNo {
            get {
                return ResourceManager.GetString("SicilNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Renewal Page Temporary URL.
        /// </summary>
        public static string SifreYenilemeSayfasiGeciciUrl {
            get {
                return ResourceManager.GetString("SifreYenilemeSayfasiGeciciUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Name.
        /// </summary>
        public static string SMTPAdi {
            get {
                return ResourceManager.GetString("SMTPAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Connection String.
        /// </summary>
        public static string SmtpBaglantiDizisi {
            get {
                return ResourceManager.GetString("SmtpBaglantiDizisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Connection Username.
        /// </summary>
        public static string SmtpBaglantiKullaniciAdi {
            get {
                return ResourceManager.GetString("SmtpBaglantiKullaniciAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Connection Password.
        /// </summary>
        public static string SmtpBaglantiSifre {
            get {
                return ResourceManager.GetString("SmtpBaglantiSifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Port.
        /// </summary>
        public static string SMTPPort {
            get {
                return ResourceManager.GetString("SMTPPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Quota Overflow Notification E-mail Postman Process Reference Number.
        /// </summary>
        public static string SonKotaAsimBildirimEpostaPostaciIslemReferansNo {
            get {
                return ResourceManager.GetString("SonKotaAsimBildirimEpostaPostaciIslemReferansNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Quota Signal E-mail Postman Process Reference Number.
        /// </summary>
        public static string SonKotaUyarımEpostaPostaciIslemReferansNo {
            get {
                return ResourceManager.GetString("SonKotaUyarımEpostaPostaciIslemReferansNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Login External System Token.
        /// </summary>
        public static string SonLoginDisSistemToken {
            get {
                return ResourceManager.GetString("SonLoginDisSistemToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Login System Token.
        /// </summary>
        public static string SonLoginSistemToken {
            get {
                return ResourceManager.GetString("SonLoginSistemToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string SoyAd {
            get {
                return ResourceManager.GetString("SoyAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Soyadi {
            get {
                return ResourceManager.GetString("Soyadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System API.
        /// </summary>
        public static string SystemApiId {
            get {
                return ResourceManager.GetString("SystemApiId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Endpoint.
        /// </summary>
        public static string SystemEndpointId {
            get {
                return ResourceManager.GetString("SystemEndpointId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar General Explanation.
        /// </summary>
        public static string TakvimAciklama {
            get {
                return ResourceManager.GetString("TakvimAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar Slicing Group Reference Number.
        /// </summary>
        public static string TakvimDilimlendirmeGrupReferansNo {
            get {
                return ResourceManager.GetString("TakvimDilimlendirmeGrupReferansNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time for Segment Spacing.
        /// </summary>
        public static string TakvimDilimlendirmeGunTipiId {
            get {
                return ResourceManager.GetString("TakvimDilimlendirmeGunTipiId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar Term Explanation.
        /// </summary>
        public static string TakvimDonemiAciklama {
            get {
                return ResourceManager.GetString("TakvimDonemiAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar Term Definition.
        /// </summary>
        public static string TakvimDonemiTanim {
            get {
                return ResourceManager.GetString("TakvimDonemiTanim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar General Definition.
        /// </summary>
        public static string TakvimGenelTanim {
            get {
                return ResourceManager.GetString("TakvimGenelTanim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar View Start Time.
        /// </summary>
        public static string TakvimGorunmeBaslangicZamani {
            get {
                return ResourceManager.GetString("TakvimGorunmeBaslangicZamani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar View End Time.
        /// </summary>
        public static string TakvimGorunmeBitisZamani {
            get {
                return ResourceManager.GetString("TakvimGorunmeBitisZamani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar Notation Color Code.
        /// </summary>
        public static string TakvimGosterimRenkKodu {
            get {
                return ResourceManager.GetString("TakvimGosterimRenkKodu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takvim Associate Company Id.
        /// </summary>
        public static string TakvimIlgiliKurumID {
            get {
                return ResourceManager.GetString("TakvimIlgiliKurumID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition.
        /// </summary>
        public static string Tanim {
            get {
                return ResourceManager.GetString("Tanim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citizenship Number.
        /// </summary>
        public static string TCKimlikNo {
            get {
                return ResourceManager.GetString("TCKimlikNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string TelefonNo {
            get {
                return ResourceManager.GetString("TelefonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Fail Text.
        /// </summary>
        public static string TestHataMetni {
            get {
                return ResourceManager.GetString("TestHataMetni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triggering Associate URL.
        /// </summary>
        public static string TetiklemeBaglantiliUrl {
            get {
                return ResourceManager.GetString("TetiklemeBaglantiliUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triggering Definition Table.
        /// </summary>
        public static string TetiklemeTanimiTablosu {
            get {
                return ResourceManager.GetString("TetiklemeTanimiTablosu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triggered Table.
        /// </summary>
        public static string TetiklemeyeKonuTablo {
            get {
                return ResourceManager.GetString("TetiklemeyeKonuTablo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Registration Number.
        /// </summary>
        public static string TicaretSicilNo {
            get {
                return ResourceManager.GetString("TicaretSicilNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Unit.
        /// </summary>
        public static string TipId {
            get {
                return ResourceManager.GetString("TipId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Ulke {
            get {
                return ResourceManager.GetString("Ulke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Name.
        /// </summary>
        public static string UlkeAdi {
            get {
                return ResourceManager.GetString("UlkeAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string UlkeId {
            get {
                return ResourceManager.GetString("UlkeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or Password.
        /// </summary>
        public static string UserNameOrMail {
            get {
                return ResourceManager.GetString("UserNameOrMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Terms of Membership Accepted.
        /// </summary>
        public static string UyelikSartiKabulEttiMi {
            get {
                return ResourceManager.GetString("UyelikSartiKabulEttiMi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Office Name.
        /// </summary>
        public static string VergiDairesiAdi {
            get {
                return ResourceManager.GetString("VergiDairesiAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Number.
        /// </summary>
        public static string VergiNo {
            get {
                return ResourceManager.GetString("VergiNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Site.
        /// </summary>
        public static string WebSitesi {
            get {
                return ResourceManager.GetString("WebSitesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Type.
        /// </summary>
        public static string YabanciDilTipi {
            get {
                return ResourceManager.GetString("YabanciDilTipi", resourceCulture);
            }
        }
    }
}
